routes/web.php
<?php
Route::get('/', function () { return redirect('/games'); });
Route::get('/games', 'GamesController@index')->name('index');
Route::get('/teams', 'TeamsController@index')->name('teams');
Route::get('/players/{team_id}', 'TeamsController@players')->name('equipe.show');
Route::get('/table', 'TableController@index');
Route::get('/groupe', 'GroupeController@index')->name('groupe');
Route::get('/Matchs', 'MatchsController@index')->name('matchs');
Route::get('/Players', 'PlayersController@index')->name('players');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('teams', 'Admin\TeamsController');
    Route::post('teams_mass_destroy', ['uses' => 'Admin\TeamsController@massDestroy', 'as' => 'teams.mass_destroy']);
    Route::resource('players', 'Admin\PlayersController');
    Route::post('players_mass_destroy', ['uses' => 'Admin\PlayersController@massDestroy', 'as' => 'players.mass_destroy']);
    Route::resource('games', 'Admin\GamesController');
    Route::post('games_mass_destroy', ['uses' => 'Admin\GamesController@massDestroy', 'as' => 'games.mass_destroy']);
    Route::resource('groupe', 'Admin\GroupeController');
    Route::post('groupe_mass_destroy', ['uses' => 'Admin\GroupeController@massDestroy', 'as' => 'groupe.mass_destroy']);

});

app/Team.php
<?php
namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Game;

/**
 * Class Team
 *
 * @package App
 * @property string $name
*/
class Team extends Model
{
    use SoftDeletes;

    protected $fillable = ['name'];

    public function players()
    {
        return $this->hasMany(Player::class);
    }
    public function groupe()
    {
        return $this->belongsToMany('App\Groupe');
    }

    public function getGamesAttribute()
    {
        return Game::where(function($query) {
            $query->where('team1_id', $this->attributes['id'])->orWhere('team2_id', $this->attributes['id']);
        })
        ->whereNotNull('result1')
        ->count();
    }

    public function getWonAttribute()
    {
        return Game::whereNotNull('result1')
            ->where(function($query) {
                $query->where(function($query2) {
                    $query2->where('team1_id', $this->attributes['id'])->whereRaw('result1 > result2');
                })->orWhere(function($query2) {
                    $query2->where('team2_id', $this->attributes['id'])->whereRaw('result1 < result2');
                });
            })
            ->count();
    }

    public function getTiedAttribute()
    {
        return Game::whereNotNull('result1')
            ->whereRaw('result1 = result2')
            ->where(function($query) {
                $query->where('team1_id', $this->attributes['id'])
                    ->orWhere('team2_id', $this->attributes['id']);
            })
            ->count();
    }

    public function getLostAttribute()
    {
        return Game::whereNotNull('result1')
            ->where(function($query) {
                $query->where(function($query2) {
                    $query2->where('team1_id', $this->attributes['id'])->whereRaw('result1 < result2');
                })->orWhere(function($query2) {
                    $query2->where('team2_id', $this->attributes['id'])->whereRaw('result1 > result2');
                });
            })
            ->count();
    }
    public function getplayedAttribute()
    {
        return $this->getGamesAttribute();

    }
    public function getPointsAttribute()
    {
        return $this->getWonAttribute() * 3 + $this->getTiedAttribute() * 1;
    }


}

resources/views/actionsTemplate.blade.php
@can($gateKey.'view')
    <a href="{{ route($routeKey.'.show', $row->id) }}"
       class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
@endcan
@can($gateKey.'edit')
    <a href="{{ route($routeKey.'.edit', $row->id) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
@endcan
@can($gateKey.'delete')
    {!! Form::open(array(
        'style' => 'display: inline-block;',
        'method' => 'DELETE',
        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
        'route' => [$routeKey.'.destroy', $row->id])) !!}
    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
    {!! Form::close() !!}
@endcan

resources/views/footer.blade.php
<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 text-center" >
                <div class="widget mb-3">
                    <h3>Tournois</h3>
                    <ul class="list-unstyled links">
                        <li><a href="{{route('teams')}}">les equipes</a></li>
                        <li><a href="{{route('players')}}">buteurs</a></li>

                    </ul>
                </div>
            </div>
            <div class="col-lg-4 text-center">
                <div class="widget mb-3">
                    <h3>Matches</h3>
                    <ul class="list-unstyled links">
                        <li><a href="{{route('groupe')}}">classement des groupes</a></li>
                        <li><a href="{{route('matchs')}}">Matchs prochaines</a></li>
                        <li><a href="{{route('matchs')}}">Résultas</a></li>

                    </ul>
                </div>
            </div>

            <div class="col-lg-4 text-center">
                <div class="widget mb-3">
                    <h3>Social</h3>
                    <ul class="list-unstyled links">
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Instagram</a></li>
                        <li><a href="#">Youtube</a></li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="row text-center">
            <div class="col-md-12">
                <div class="pt-5">
                    <p>
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | This template is made with
                        <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">
                            Colorlib</a>
                    </p>
                </div>
                    <p>
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | Tournois at vugharden was devlopped by <a href="https://bylka.net">SAID</a>
                    </p>
            </div>

        </div>
    </div>
</footer>

resources/views/groupe.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Les groupes</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">

    <link rel="stylesheet" href="css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/style.css">



</head>

<body>

<div class="site-wrap">

    @include('header')

    <div class="hero overlay" style="background-image: url('images/bg_3.jpg');">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 ml-auto">
                    <h1 class="text-white text-center">TOURNOIS <br/>AT VUƔARDEN</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section py-5">
        <div class="container">
            <div class="row mb-3">
                <div class="col-6 title-section ">
                    <h2 class="heading">Groupes</h2>
                </div>
                <div class="col-6 text-right">
                    <div class="custom-nav">
                        <a href="#" class="js-custom-prev-v2"><span class="icon-keyboard_arrow_left"></span></a>
                        <span></span>
                        <a href="#" class="js-custom-next-v2"><span class="icon-keyboard_arrow_right"></span></a>
                    </div>
                </div>
            </div>


            <div class="owl-4-slider owl-carousel">
                @foreach($groupes as $groupe)
                    <div class="item">
                        <div class="col-6 title-section  text-center mb-3 m-auto">
                            <h1 class="site-section-heading text-white mb-5">Groupe "{{$groupe->name}}" </h1>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">

                                <div class="widget-next-match table-responsive">
                                    <table class="table custom-table">
                                        <thead>
                                        <tr>

                                            <th>Team</th>
                                            <th>P</th>
                                            <th>W</th>
                                            <th>D</th>
                                            <th>L</th>
                                            <th>PTS</th>
                                        </tr>
                                        </thead>
                                        @foreach($groupe->team()->get()->sortByDesc('points') as $team)
                                            <tbody>
                                            <tr>

                                                <td><a href="{{route('equipe.show',$team->id)}}"><strong class="text-white">{{$team->name}}</strong></a></td>
                                                <td>{{ $team->played }}</td>
                                                <td>{{ $team->won }}</td>
                                                <td>{{ $team->tied }}</td>
                                                <td>{{ $team->lost }}</td>
                                                <td>{{ $team->points }}</td>
                                            </tr>
                                            @endforeach
                                            </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

        </div>
    </div>



    @include('footer')



</div>
<!-- .site-wrap -->

<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/jquery-migrate-3.0.1.min.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.stellar.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/bootstrap-datepicker.min.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/aos.js"></script>
<script src="js/jquery.fancybox.min.js"></script>
<script src="js/jquery.sticky.js"></script>
<script src="js/jquery.mb.YTPlayer.min.js"></script>


<script src="js/main.js"></script>

</body>

</html>

resources/views/header.blade.php
<div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
            <span class="icon-close2 js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body"></div>
</div>


<header class="site-navbar py-4" role="banner">

    <div class="container">
        <div class="d-flex align-items-center">
            <div class="site-logo">
                <a href="{{route('index')}}">
                    <img src="{{asset('images/logo.png')}}" alt="Logo">
                </a>
            </div>
            <div class="ml-auto">
                <nav class="site-navigation position-relative text-right" role="navigation">
                    <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                        <li class="{{ (request()->is('games')) ? 'active' : '' }}"><a href="{{route('index')}}" class="nav-link">Acceuil</a></li>
                        <li class="{{ (request()->is('Matchs')) ? 'active' : '' }}"><a href="{{route('matchs')}}" class="nav-link">Matches et Résultats</a></li>
                        <li class="{{ (request()->is('groupe')) ? 'active' : '' }}"><a href="{{route('groupe')}}" class="nav-link">Classement et Groupes</a></li>
                        <li class="{{ (request()->is('Players')) ? 'active' : '' }}"><a href="{{route('players')}}" class="nav-link">Buteurs</a></li>
                        <li class="{{ (request()->is('teams')) ? 'active' : '' }}"><a href="{{route('teams')}}" class="nav-link">Equipes</a></li>
                    </ul>
                </nav>

                <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right text-white"><span
                            class="icon-menu h3 text-white"></span></a>
            </div>
        </div>
    </div>

</header>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tournois At vugarden</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">

    <link rel="stylesheet" href="css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/style.css">



</head>

<body>

<div class="site-wrap">

    @include('header')

    <div class="hero overlay" style="background-image: url('{{asset('images/bg_0.jpg')}}');">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 ml-auto">
                    <h1 class="text-white text-center">TOURNOIS <br/>AT VUƔARDEN</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container py-5">
            <div class="row">
                @foreach($nextmatch as $game)
                    <div class="col-lg-12 m-auto">
                        <div class="widget-next-match">
                            <div class="widget-title  text-center">
                                <h2>Prochaine  match</h2>
                            </div>

                            <div class="widget-body mb-1">
                                <div class="widget-vs">
                                    <div class="d-flex align-items-center justify-content-around justify-content-between w-100">
                                        <div class="team-1 text-center">
                                            <img src="images/logo_1.png" alt="Image">
                                            <h3>{{ $game->team1->name }}</h3>
                                        </div>
                                        <div>
                                            <span class="vs"><span>VS</span></span>
                                        </div>
                                        <div class="team-2 text-center">
                                            <img src="images/logo_2.png" alt="Image">
                                            <h3>{{ $game->team2->name }}</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center widget-vs-contents mb-1">
                                <p class="mb-2">
                                    <span class="d-block">{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $game->start_time)->format('d-m-Y') }}</span>
                                    <span class="d-block">{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $game->start_time)->format('H:i') }}</span>
                                </p>
                            </div>

                        </div>

                    </div>
                @endforeach
            </div>
        </div>
    </div> <!-- .site-section -->

    <div class="container teams result">
        <div class="col-12 title-section">
            <h2 class="heading">Derniers matchs</h2>
        </div>
        <div class="row">
            @foreach($results as $game)
            <div class="col-lg-6 m-auto">
                <div class="d-flex team-vs">
                    <span class="score">{{ $game->result1 }} - {{ $game->result2 }}</span>
                    <div class="team-1 w-50">
                        <div class="team-details w-100 text-center">
                            <img src="images/logo_1.png" alt="Image" class="img-fluid">
                            <h3>{{ $game->team1->name }}</h3>
                        </div>
                    </div>
                    <div class="team-2 w-50">
                        <div class="team-details w-100 text-center">
                            <img src="images/logo_2.png" alt="Image" class="img-fluid">
                            <h3>{{ $game->team2->name }}</h3>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>

    <div class="latest-news mb-3">
        <div class="container">
            <div class="row">
                <div class="col-12 title-section">
                    <h2 class="heading">Photos</h2>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-md-4">
                    <div class="post-entry">
                        <a href="#">
                            <img src="{{asset('images/img_5.jpg')}}" alt="Image" class="img-fluid">
                        </a>
                     </div>
                </div>
                <div class="col-md-4">
                    <div class="post-entry">
                        <a href="#">
                            <img src="{{asset('images/img_6.jpg')}}" alt="Image" class="img-fluid">
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="post-entry">
                        <a href="#">
                            <img src="{{asset('images/img_4.jpg')}}" alt="Image" class="img-fluid">
                        </a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="site-section mb-5 py-5">
        <div class="container">
            <div class="row">
                <div class="col-6 title-section">
                    <h2 class="heading">Groupes</h2>
                </div>
                <div class="col-6 text-right">
                    <div class="custom-nav">
                        <a href="#" class="js-custom-prev-v2"><span class="icon-keyboard_arrow_left"></span></a>
                        <span></span>
                        <a href="#" class="js-custom-next-v2"><span class="icon-keyboard_arrow_right"></span></a>
                    </div>
                </div>
            </div>


            <div class="owl-4-slider owl-carousel">
                @foreach($groupes as $groupe)
                <div class="item">
                    <div class="col-6 title-section  text-center mb-3 m-auto">
                        <h1 class="site-section-heading text-white mb-5">Groupe "{{$groupe->name}}" </h1>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="widget-next-match">
                                <div class="widget-title">
                                    <h3>Prochaines matches</h3>
                                </div>
                                @foreach($groupe->game()->whereNull('result1')->get() as $game)
                                <div class="widget-body">
                                    <div class="widget-vs">
                                        <div class="d-flex align-items-center justify-content-around justify-content-between w-100">
                                            <div class="team-1 text-center">
                                                <img src="images/logo_1.png" alt="Image" class="img-fluid" width="75">
                                                <h3>{{ $game->team1->name}}</h3>
                                            </div>
                                            <div class="text-center">
                                                <span class="vs"><span>VS</span></span>
                                                <span class="d-block">{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $game->start_time)->format('Y-m-d') }}</span>
                                                <span class="d-block">{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $game->start_time)->format('H:i') }}</span>
                                            </div>
                                            <div class="team-2 text-center">
                                                <img src="images/logo_2.png" alt="Image"  width="75">
                                                <h3>{{ $game->team2->name}}</h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                                <div class="text-center widget-vs-contents mb-4">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">

                            <div class="widget-next-match table-responsive">
                                <table class="table custom-table">
                                    <thead>
                                    <tr>

                                        <th>Team</th>
                                        <th>P</th>
                                        <th>W</th>
                                        <th>D</th>
                                        <th>L</th>
                                        <th>PTS</th>
                                    </tr>
                                    </thead>
                                     @foreach($groupe->team()->get()->sortByDesc('points') as $team)
                                    <tbody>
                                    <tr>

                                        <td><strong class="text-white">{{$team->name}}</strong></td>
                                        <td>{{ $team->played }}</td>
                                        <td>{{ $team->won }}</td>
                                        <td>{{ $team->tied }}</td>
                                        <td>{{ $team->lost }}</td>
                                        <td>{{ $team->points }}</td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
                @endforeach
            </div>

        </div>
    </div>



    @include('footer')



</div>
<!-- .site-wrap -->

<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/jquery-migrate-3.0.1.min.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.stellar.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/bootstrap-datepicker.min.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/aos.js"></script>
<script src="js/jquery.fancybox.min.js"></script>
<script src="js/jquery.sticky.js"></script>
<script src="js/jquery.mb.YTPlayer.min.js"></script>


<script src="js/main.js"></script>

</body>

</html>

resources/views/players.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Joueurs</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">

    <link rel="stylesheet" href="css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/style.css">



</head>

<body>

<div class="site-wrap">

    @include('header')

    <div class="hero overlay mb-5" style="background-image: url('images/bg_3.jpg');">
        <div class="container">
            <div class="row align-items-center ">
                <div class="col-lg-5 mx-auto text-center">
                    <h1 class="text-white">Buteurs</h1>
                    <p>Liste des meilleurs buteurs du tournois </p>
                </div>
            </div>
        </div>
    </div>
<div class="container">
    <div class="col-lg-12 m-auto ">

        <div class="widget-next-match mb-5">
            <table class="table custom-table">
                <thead>
                <tr>
                    <th class="text-center">Nom</th>
                    <th class="text-center">Prénom</th>
                    <th class="text-center">Buts</th>
                    <th class="text-center">Passe décisif</th>
                    <th class="text-center">Carton jaune</th>
                    <th class="text-center">Carton rouge</th>
                    <th class="text-center">Equipe</th>
                </tr>
                </thead>

                    <tbody>
                    @foreach($players as $player)
                    <tr>
                        <td class="text-center"><strong class="text-white">{{$player->name}}</strong></td>
                        <td class="text-center"><strong class="text-white">{{$player->surname}}</strong></td>
                        <td class="text-center"><strong class="text-white">{{$player->buts}}</strong></td>
                        <td class="text-center"><strong class="text-white">{{$player->assist}}</strong></td>
                        <td class="text-center"><strong class="text-white">{{$player->carton_jaune}}</strong></td>
                        <td class="text-center"><strong class="text-white">{{$player->carton_rouge}}</strong></td>
                        <td class="text-center"><strong class="text-white">{{$player->team->name}}</strong></td>
                    </tr>
                        @endforeach

                    </tbody>
            </table>
        </div>

    </div>
</div>








   @include('footer')



</div>
<!-- .site-wrap -->

<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/jquery-migrate-3.0.1.min.js"></script>
<script src="js/jquery-ui.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/jquery.stellar.min.js"></script>
<script src="js/jquery.countdown.min.js"></script>
<script src="js/bootstrap-datepicker.min.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/aos.js"></script>
<script src="js/jquery.fancybox.min.js"></script>
<script src="js/jquery.sticky.js"></script>
<script src="js/jquery.mb.YTPlayer.min.js"></script>


<script src="js/main.js"></script>

</body>

</html>